### ISSUE TITLE
'Unable to load 'csfml-audio-2.4.0' (Windows).'

### ISSUE THREAD

**Issue by devilsk** [intechinfo/ITI-SFML#7]
hello ,

SFML.AudioNative.Load();
throw : 
System.IO.FileNotFoundException : 'Unable to load 'csfml-audio-2.4.0' (Windows).'

**Comment by olivier-spinelli** [comment]
Has this been done?
https://github.com/intechinfo/ITI-SFML/blob/792c24a5ab333a7e14cf2c9894f158a28bf81185/Tests/DemoApp/Program.cs#L15

**Comment by Kuinox** [comment]
SFML.AudioNative.Load(); Should not need Graphics ?
I modified DemoApp and put it right after SFML.GraphicsNative.Load(); and it don't work.

**Comment by olivier-spinelli** [comment]
The answer seems to be here: https://en.sfml-dev.org/forums/index.php?topic=16728.0
I'm on it.

**Comment by olivier-spinelli** [comment]
Version 0.1.0 (available on myget intech-release feed) should fix the problem.

**Comment by devilsk** [comment]
thanks ! v0.1.0 solve the issue
